# Generated by Django 4.2 on 2023-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
