# Generated by Django 4.2 on 2023-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_categorymodel_jobmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='jobsImages/'),
        ),
    ]
