# Generated by Django 4.2 on 2023-04-23 21:49

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=job.models.JobModel.imageGenerator),
        ),
    ]
