# Generated by Django 4.2 on 2023-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_candidates_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
