# Generated by Django 4.2 on 2023-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_candidates_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='coverLetter',
            field=models.TextField(max_length=100),
        ),
    ]
