# Generated by Django 4.2 on 2023-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_candidates_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='published_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
